const MAX_BYTES=12*1024*1024;
const TIMEOUT_MS=8000;
function json(data,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
function privateHost(host){const h=String(host||'').toLowerCase().replace(/^\[|\]$/g,'');if(!h||h==='localhost'||h.endsWith('.local')||h.endsWith('.internal'))return true;if(/^(127\.|0\.|10\.|192\.168\.|169\.254\.)/.test(h))return true;const m=/^172\.(\d{1,3})\./.exec(h);if(m&&Number(m[1])>=16&&Number(m[1])<=31)return true;return h==='::1'||h.startsWith('fc')||h.startsWith('fd')||h.startsWith('fe80:');}
export function validateAssetUrl(value){let u;try{u=new URL(String(value||''));}catch{throw new Error('URL de asset inválida.');}if(!/^https?:$/.test(u.protocol)||privateHost(u.hostname))throw new Error('URL de asset não permitida.');return u;}
function cacheRequest(request,url){const key=new URL(request.url);key.pathname='/__ronda_asset_cache/'+encodeURIComponent(url.toString());key.search='';return new Request(key.toString(),{method:'GET'});}
async function fetchWithTimeout(url){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),TIMEOUT_MS);try{return await fetch(url,{signal:ctrl.signal,redirect:'follow',headers:{'Accept':'image/avif,image/webp,image/png,image/jpeg,image/gif,image/*;q=0.8,*/*;q=0.2','User-Agent':'RondaOne/0.9.5 asset-proxy'}});}finally{clearTimeout(timer);}}
export async function handleAssetProxyApi(request){const u=new URL(request.url);if(u.pathname!=='/api/assets/proxy')return null;if(request.method!=='GET'&&request.method!=='HEAD')return json({ok:false,error:'Método não permitido.'},405);let source;try{source=validateAssetUrl(u.searchParams.get('url'));}catch(error){return json({ok:false,error:error.message},400);}const cache=globalThis.caches?.default;const key=cacheRequest(request,source);if(cache){const hit=await cache.match(key);if(hit){const h=new Headers(hit.headers);h.set('X-Ronda-Asset-Cache','HIT');return new Response(request.method==='HEAD'?null:hit.body,{status:hit.status,headers:h});}}
  let response;try{response=await fetchWithTimeout(source);}catch(error){return json({ok:false,error:'Asset externo temporariamente indisponível.',detail:String(error?.message||error).slice(0,240)},502);}if(!response.ok)return json({ok:false,error:`Asset externo respondeu HTTP ${response.status}.`},502);const type=String(response.headers.get('content-type')||'').toLowerCase();if(!type.startsWith('image/'))return json({ok:false,error:'O recurso externo não é uma imagem válida.'},415);const declared=Number(response.headers.get('content-length')||0);if(declared>MAX_BYTES)return json({ok:false,error:'Imagem externa excede o limite seguro de 12 MB.'},413);const bytes=await response.arrayBuffer();if(bytes.byteLength>MAX_BYTES)return json({ok:false,error:'Imagem externa excede o limite seguro de 12 MB.'},413);const headers=new Headers({'Content-Type':type||'application/octet-stream','Cache-Control':'public, max-age=86400, stale-while-revalidate=604800','X-Content-Type-Options':'nosniff','X-Ronda-Asset-Source':source.hostname,'X-Ronda-Asset-Cache':'MISS'});const out=new Response(request.method==='HEAD'?null:bytes,{status:200,headers});if(cache&&request.method==='GET')await cache.put(key,new Response(bytes,{status:200,headers})).catch(()=>null);return out;}
