import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const pkg=JSON.parse(read('package.json'));
const platform=read('src/index.js');
const shell=read('src/ronda/shell.js');
const worker=read('src/ronda/v285/index.js');
const events=read('src/ronda/editorial-events.js');
const mesa=read('public/ronda/editorial-mesa.js');
const readme=read('README.md');
assert.equal(pkg.version,'0.9.2');
assert.match(platform,/version:'0\.9\.2'/);
assert.match(platform,/editorialVersion:'2\.9\.2'/);
assert.match(shell,/PLATFORM_VERSION='0\.9\.2'/);
assert.match(worker,/const VERSION = "2\.9\.2"/);
assert.match(events,/function apuracaoQuality/);
assert.match(events,/function editorialAction/);
assert.match(events,/qualidadeApuracao/);
assert.match(events,/acaoEditorial/);
assert.match(mesa,/eventSourceHealthSummary/);
assert.match(mesa,/renderEventHistory/);
assert.match(readme,/v0\.9\.2/);
console.log('RONDA ONE v0.9.2: verificação estrutural OK');
