import assert from "node:assert/strict";
import fs from "node:fs";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const pkg=JSON.parse(read("package.json"));
const platform=read("src/index.js");
const worker=read("src/ronda/v285/index.js");
const collector=read("src/ronda/v285/collector.js");
const scraper=read("src/ronda/v285/scraper.js");
const app=read("public/ronda/app.js");
const wrangler=read("wrangler.jsonc");
const design=read("public/design/index.html");
assert.equal(pkg.version,"0.9.0");
assert.match(platform,/fastNewsEngineV090/);
assert.match(wrangler,/"\* \* \* \* \*"/);
assert.match(worker,/minute % 3 === 0 \? "full" : "fast"/);
assert.match(worker,/INTELLIGENT_JOB_LOCK_TTL_MS = 90 \* 1000/);
assert.match(worker,/EDITORIAL_ROUND_LOCK_TTL_MS = 3 \* 60 \* 1000/);
assert.match(worker,/sourceStateDiagnosticsAsStatuses/);
assert.match(collector,/FAST_LANE_FEEDS/);
assert.match(collector,/parseNewsHtml/);
assert.match(collector,/firstSeenAt/);
assert.match(scraper,/html-jsonld/);
assert.match(app,/function itemRadarTime/);
assert.match(app,/Detectado/);
assert.match(app,/rescueAttempts >= 3/);
assert.match(design,/A matéria já está sendo processada pela fila/);
console.log("RONDA ONE v0.9.0: verificações estruturais OK.");
