import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const pkg=JSON.parse(read('package.json'));
const platform=read('src/index.js');
const shell=read('src/ronda/shell.js');
const worker=read('src/ronda/v285/index.js');
const router=read('src/ronda/router.js');
const events=read('src/ronda/editorial-events.js');
const reliability=read('src/reliability/core.js');
const assetProxy=read('src/ronda/asset-proxy.js');
const production=read('src/production/engine.js');
const scraping=read('src/production/scraping-engine.js');
const smart=read('public/design/smart-template-engine.js');
const design=read('public/design/index.html');
const ronda=read('public/ronda/app.js');
const wrangler=JSON.parse(read('wrangler.jsonc'));
const readme=read('README.md');
assert.equal(pkg.version,'0.9.7');
assert.match(platform,/version:'0\.9\.7'/);
assert.match(platform,/editorialVersion:'2\.9\.7'/);
assert.match(shell,/PLATFORM_VERSION='0\.9\.7'/);
assert.match(shell,/RONDA_EDITORIAL_VERSION='2\.9\.7'/);
assert.match(worker,/const VERSION = "2\.9\.7"/);
assert.match(platform,/reliabilityCoreV093/);
assert.match(platform,/productionHardeningV094/);
assert.match(platform,/formaProductionEngineV096/);
assert.match(platform,/scrapingEvidenceEngineV097/);
assert.match(reliability,/completed_fallback/);
assert.match(worker,/autoRecoverStaleIntelligentJobs/);
assert.match(events,/feed-fallback/);
assert.match(assetProxy,/X-Ronda-Asset-Cache/);
assert.match(smart,/preflightTemplate/);
assert.match(smart,/defaultTemplate/);
assert.match(design,/\/api\/production\/jobs/);
assert.match(design,/\/api\/production\/image/);
assert.match(design,/Evidence Pack/);
assert.match(ronda,/Produzir no FORMA/);
assert.match(router,/runProductionQueue/);
assert.match(production,/production_jobs/);
assert.match(production,/evidence_packages/);
assert.match(production,/ARTICLE_READ_QUEUE/);
assert.match(production,/CAROUSEL_AI_QUEUE/);
assert.match(scraping,/PORTAL_ADAPTERS/);
assert.match(scraping,/id:"g1"/);
assert.match(scraping,/collected-fallback/);
assert.ok(wrangler.queues.producers.some(x=>x.binding==='ARTICLE_READ_QUEUE'));
assert.ok(wrangler.queues.producers.some(x=>x.binding==='CAROUSEL_AI_QUEUE'));
assert.match(readme,/v0\.9\.7/);
console.log('RONDA ONE v0.9.7: verificação estrutural OK');
