import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const pkg=JSON.parse(read('package.json'));
const platform=read('src/index.js');
const shell=read('src/ronda/shell.js');
const worker=read('src/ronda/v285/index.js');
const router=read('src/ronda/router.js');
const events=read('src/ronda/editorial-events.js');
const reliability=read('src/reliability/core.js');
const assetProxy=read('src/ronda/asset-proxy.js');
const production=read('src/production/engine.js');
const scraping=read('src/production/scraping-engine.js');
const collector=read('src/ronda/v285/collector.js');
const database=read('src/ronda/v285/database.js');
const reader=read('src/ronda/v285/article-reader.js');
const smart=read('public/design/smart-template-engine.js');
const design=read('public/design/index.html');
const ronda=read('public/ronda/app.js');
const wrangler=JSON.parse(read('wrangler.jsonc'));
const readme=read('README.md');
assert.equal(pkg.version,'0.9.7.5.7');
assert.match(platform,/version:'0\.9\.7\.5\.7'/);
assert.match(platform,/editorialVersion:'2\.9\.7\.5\.7'/);
assert.match(shell,/PLATFORM_VERSION='0\.9\.7\.5\.7'/);
assert.match(shell,/RONDA_EDITORIAL_VERSION='2\.9\.7\.5\.7'/);
assert.match(worker,/const VERSION = "2\.9\.7\.5\.7"/);
assert.match(platform,/reliabilityCoreV093/);
assert.match(platform,/productionHardeningV094/);
assert.match(platform,/formaProductionEngineV096/);
assert.match(platform,/scrapingEvidenceEngineV097/);
assert.match(platform,/fastCarouselSourceCreditsV0971/);
assert.match(platform,/singleSourceContentFirstV0972/);
assert.match(platform,/mandatorySlideCountV09721/);
assert.match(platform,/interactiveFastPathV0973/);
assert.match(platform,/fastRonda25PlusV0974/);
assert.match(platform,/adaptiveScrapingV09745/);
assert.match(platform,/hybridMultiTransportV09746/);
assert.match(platform,/highVolumeDiscoveryV09747/);
assert.match(scraping,/evidenceSufficiency/);
assert.match(scraping,/json-ld-fast/);
assert.match(production,/launchInteractiveProduction/);
assert.match(production,/findActiveProductionJob/);
assert.match(events,/sinceLastRound/);
assert.match(collector,/hasSafeSnapshot/);
assert.match(reliability,/completed_fallback/);
assert.match(worker,/autoRecoverStaleIntelligentJobs/);
assert.match(events,/feed-fallback/);
assert.match(assetProxy,/X-Ronda-Asset-Cache/);
assert.match(smart,/preflightTemplate/);
assert.match(smart,/defaultTemplate/);
assert.match(design,/\/api\/production\/jobs/);
assert.match(design,/\/api\/production\/image/);
assert.match(design,/Evidence Pack/);
assert.match(ronda,/Produzir no FORMA/);
assert.match(router,/runProductionQueue/);
assert.match(production,/production_jobs/);
assert.match(production,/production_stage_leases/);
assert.match(production,/evidence_packages/);
assert.match(production,/runInteractiveProduction/);
assert.match(reader,/buildCarouselFromEvidencePack/);
assert.match(production,/mode:"evidence-first"/);
assert.match(collector,/earlySourceTarget = 25/);
assert.match(collector,/skipScrapeWhenDirectHealthy: true/);
assert.match(database,/latest_round_preview/);
assert.match(database,/source_discovery_items/);
assert.match(collector,/sourceVolumeProfile/);
assert.match(collector,/parseDiscoveryHtml/);
assert.match(scraping,/PORTAL_ADAPTERS/);
assert.match(scraping,/id:"g1"/);
assert.match(scraping,/collected-fallback/);
assert.ok(wrangler.queues.producers.some(x=>x.binding==='ARTICLE_READ_QUEUE'));
assert.ok(wrangler.queues.producers.some(x=>x.binding==='CAROUSEL_AI_QUEUE'));
assert.equal(wrangler.browser?.binding,'BROWSER');
assert.match(production,/BROWSER\.quickAction\("content"/);
assert.match(production,/production_transport_stats/);
assert.match(scraping,/transportPreference/);
assert.match(scraping,/id:"band"/);
assert.match(readme,/v0\.9\.7\.4\.9/);
assert.match(platform,/noHangProductionV09722/);
assert.match(production,/recoverStalledProductionJob/);
assert.match(design,/directArticleRetry/);
assert.match(design,/retryLastFormaProduction/);
assert.match(production,/Nova tentativa solicitada pelo operador/);
assert.match(platform,/hotfixLockV09748/);
assert.match(platform,/editorialDeskTrackingV09749/);
assert.match(database,/editorial_production_tracking/);
assert.match(design,/markEditorialProductionComplete/);
assert.match(ronda,/editorialEventId/);
assert.match(platform,/coveragePercent/);
assert.match(collector,/sourceCircuitDecision/);
assert.match(collector,/collectSourceRevalidation/);
assert.match(database,/circuit_state/);
assert.match(database,/revalidation_pending/);
assert.match(worker,/source-revalidate/);
assert.match(worker,/ROUTE_NOT_FOUND/);
assert.match(platform,/qualityFirstV09757/);
assert.match(platform,/costGovernorV09757/);
assert.match(platform,/crawlReadOnlyV09757/);
assert.equal(wrangler.triggers.crons[0],'*/5 * * * *');
console.log('RONDA ONE v0.9.7.5.7: verificação estrutural OK');
